-------------------------------------------------------------------------------
Test set: Main screen is visible
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 60.421 s <<< FAILURE! - in Main screen is visible
Main screen is visible.The main screen is displayed and functions  Time elapsed: 60.421 s  <<< ERROR!
org.openqa.selenium.SessionNotCreatedException: 
Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not acquire lock on /var/folders/6j/tstynf051y3059t221wl384c0000gn/T/uia2_device_port_guard. Original error: Error: EEXIST: file already exists, open '/var/folders/6j/tstynf051y3059t221wl384c0000gn/T/uia2_device_port_guard'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Marks-iMac.local', ip: '192.168.1.87', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_131'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not acquire lock on /var/folders/6j/tstynf051y3059t221wl384c0000gn/T/uia2_device_port_guard. Original error: Error: EEXIST: file already exists, open '/var/folders/6j/tstynf051y3059t221wl384c0000gn/T/uia2_device_port_guard'
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:381:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Marks-iMac.local', ip: '192.168.1.87', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_131'
Driver info: driver.version: AndroidDriver
Caused by: java.lang.reflect.InvocationTargetException
Caused by: org.openqa.selenium.WebDriverException: 
An unknown server-side error occurred while processing the command. Original error: Could not acquire lock on /var/folders/6j/tstynf051y3059t221wl384c0000gn/T/uia2_device_port_guard. Original error: Error: EEXIST: file already exists, open '/var/folders/6j/tstynf051y3059t221wl384c0000gn/T/uia2_device_port_guard'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Marks-iMac.local', ip: '192.168.1.87', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_131'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not acquire lock on /var/folders/6j/tstynf051y3059t221wl384c0000gn/T/uia2_device_port_guard. Original error: Error: EEXIST: file already exists, open '/var/folders/6j/tstynf051y3059t221wl384c0000gn/T/uia2_device_port_guard'
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:381:37)

